##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2018                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

##########################################################################
#                                                                        #
# Define variables from configure.                                       #
# These variables may be redefined later.                                #
#                                                                        #
##########################################################################

######################
# Installation paths #
######################

CYGPATH         ?=

DESTDIR 	?=
prefix		?=/root/.opam/default
exec_prefix	?=${prefix}
datarootdir     ?=${prefix}/share
datadir         ?=${datarootdir}
BINDIR		?="$(DESTDIR)${exec_prefix}/bin"
LIBDIR		?="$(DESTDIR)${exec_prefix}/lib"
DATADIR		?="$(DESTDIR)${prefix}/share"
MANDIR		?="$(DESTDIR)${datarootdir}/man"

FRAMAC_LIBDIR	?=$(LIBDIR)/frama-c
FRAMAC_PLUGINDIR ?=$(FRAMAC_LIBDIR)/plugins
FRAMAC_DATADIR 	?=$(DATADIR)/frama-c
EMACS_DATADIR	?=$(DATADIR)/emacs/site-lisp
FRAMAC_DEFAULT_CPP ?=gcc -E -C -I.
FRAMAC_DEFAULT_CPP_ARGS ?= -C -I.
FRAMAC_GNU_CPP ?=true
DEFAULT_CPP_KEEP_COMMENTS?=true
DEFAULT_CPP_SUPPORTED_ARCH_OPTS?=\"-m32\"; \"-m64\"; \"-m16\"; 
CC =gcc

###############
# Ocaml stuff #
###############

# compilers and others executables
OCAMLC  	?=ocamlfind ocamlc
OCAMLOPT	?=ocamlfind ocamlopt
OCAMLDEP	?=ocamlfind ocamldep -slash
OCAMLLEX	?=ocamllex.opt
OCAMLYACC	?=ocamlyacc
OCAMLMKTOP	?=ocamlfind ocamlmktop
OCAMLDOC	?=ocamlfind ocamldoc
OCAMLCP		?=ocamlfind ocamlcp

# others ocaml stuffs

# either -annot or -dtypes
OCAML_ANNOT_OPTION ?=-bin-annot
# ocaml stdlib path
OCAMLLIB	?=/root/.opam/default/lib/ocaml
# either opt or byte
OCAMLBEST	?=opt
OCAMLVERSION 	?=4.07.0
NATIVE_THREADS	?=yes
OCAMLWIN32	?=no
PTESTSBEST      ?=opt

DEVELOPMENT	?=no

# Compatibility across OCaml versions

SPLIT_ON_CHAR ?= String.split_on_char
STACK_FOLD ?= Stack.fold

#############
# Libraries #
#############

# lablgtk
HAS_LABLGTK	?=no
HAS_LABLGTK_CUSTOM_MODEL ?=no
LABLGTK_PATH ?=+lablgtk2

# lablgtksourceview
HAS_GTKSOURCEVIEW ?=no

# lablgnomecanvas
HAS_GNOMECANVAS	?=no

# yojson
HAS_YOJSON	?=no

# apron
HAS_APRON	?=no

# landmarks
HAS_LANDMARKS	?=no

##########################
# Miscellaneous commands #
##########################

OTAGS		?=
DOT		?=dot
HAS_DOT		?=yes

HEADACHE 	?= headache -c $(FRAMAC_SRC)/headers/headache_config.txt

###########################
# Miscellaneous variables #
###########################

VERBOSEMAKE	?=no
LOCAL_MACHDEP	?=no
EXE		?=

# Required by Cil
UNDERSCORE_NAME ?=
HAVE_BUILTIN_VA_LIST ?=
THREAD_IS_KEYWORD ?=

##########################
# Variables for plug-ins #
##########################

EXTERNAL_PLUGINS ?= 

# Integrated plugins
ENABLE_CALLGRAPH                  ?=no
ENABLE_CONSTANT_PROPAGATION       ?=no
ENABLE_FROM_ANALYSIS              ?=no
ENABLE_GUI	                  ?=no
ENABLE_IMPACT	                  ?=no
ENABLE_INOUT	                  ?=no
ENABLE_METRICS	                  ?=no
ENABLE_OCCURRENCE                 ?=no
ENABLE_PDG	                  ?=no
ENABLE_POSTDOMINATORS             ?=no
ENABLE_RTEGEN                     ?=no
ENABLE_SCOPE	                  ?=no
ENABLE_SLICING	                  ?=no
ENABLE_SPARECODE                  ?=no
ENABLE_USERS	                  ?=no
ENABLE_VALUE_ANALYSIS             ?=no

#bytes is part of the stdlib, but is used as a transitional package.
LIBRARY_NAMES := findlib ocamlgraph unix str dynlink bytes zarith

ifeq ($(HAS_LANDMARKS),yes)
LIBRARY_NAMES += landmarks landmarks.ppx
endif

ifeq ($(HAS_YOJSON),yes)
LIBRARY_NAMES += yojson
endif

ifneq ($(ENABLE_GUI),no)
LIBRARY_NAMES_GUI = lablgtk2 lablgtk2.gnomecanvas lablgtk2.sourceview2
else
LIBRARY_NAMES_GUI =
endif

#######################
# Working directories #
#######################

ifeq ($(OCAMLWIN32),yes)
ifneq ($(CYGPATH),no)
# Note: using quotes in the line below leads to weird garbled characters
# in some versions of Cygwin.
winpath=$(shell $(CYGPATH) -m $(1))
else
winpath=$(1)
endif #CYGPATH
else
winpath=$(1)
endif #OCAMLWIN32

FRAMAC_ROOT_SRCDIR 	?= $(call winpath,/home/u1364447/frama-c-Chlorine-20180502)

##########################################################################
# Local Variables:
# mode: makefile
# End:
